# Generated by Django 3.0.6 on 2020-05-23 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/profiles')),
                ('bio', models.TextField(max_length=250, null=True)),
                ('githib', models.CharField(blank=True, max_length=750, null=True)),
                ('trello', models.CharField(blank=True, max_length=750, null=True)),
                ('instagram', models.CharField(blank=True, max_length=750, null=True)),
                ('email', models.CharField(blank=True, max_length=750, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=750, null=True)),
                ('twitter', models.CharField(blank=True, max_length=750, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
