# Generated by Django 3.0.6 on 2020-05-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'رویداد', 'verbose_name_plural': 'رویدادها'},
        ),
    ]
