# Generated by Django 3.0.6 on 2020-05-30 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0003_auto_20200524_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='githib',
            new_name='github',
        ),
    ]
