# Generated by Django 3.0.6 on 2020-08-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0005_auto_20200715_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='درباره شما'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=750, null=True, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.CharField(blank=True, max_length=750, null=True, verbose_name='آدرس گیت\u200cهاب شما'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, max_length=750, null=True, verbose_name='آدرس اینستاگرام شما'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=False, null=True, verbose_name='وضعیت ادمینی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_author',
            field=models.BooleanField(default=False, null=True, verbose_name='وضعیت نویسندگی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=750, null=True, verbose_name='آدرس لینکدین شما'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='trello',
            field=models.CharField(blank=True, max_length=750, null=True, verbose_name='آدرس ترلو شما'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=750, null=True, verbose_name='آدرس توییتر شما'),
        ),
    ]
