# Generated by Django 3.0.6 on 2020-05-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('description', models.TextField(max_length=9500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', models.DateField()),
            ],
        ),
    ]
