# Generated by Django 3.0.6 on 2020-05-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='file_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='person',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('a', 'به اتمام رسیده'), ('b', 'آغاز شده'), ('c', 'برگزار نشده')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
