# Generated by Django 3.0.6 on 2020-05-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0003_auto_20200521_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='summary',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
