# Generated by Django 3.0.6 on 2020-08-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0003_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='addres',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('a', 'مجازی'), ('b', 'حضوری')], max_length=1, null=True, verbose_name='نوع رویداد'),
        ),
    ]
