# Generated by Django 3.0.6 on 2020-05-23 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0004_event_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
