# Generated by Django 3.0.6 on 2020-08-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0004_auto_20200830_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='addres',
            field=models.TextField(blank=True, help_text='آدرس محل و یا لینک دسترسی به رویداد را در این قسمت قرار دهید', max_length=500, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='event',
            name='file_url',
            field=models.FileField(blank=True, help_text='در صورتی که مایل به اشتراک گذاری فایل استفاده شده در رویداد هستید از این قسمت وارد کنید.', null=True, upload_to='uploads/admin', verbose_name='فایل'),
        ),
    ]
