# Generated by Django 3.0.6 on 2020-05-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0006_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=200, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=250, null=True, verbose_name='عنوان'),
        ),
    ]
