# Generated by Django 3.0.6 on 2020-05-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0007_auto_20200524_0224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'رویداد', 'verbose_name_plural': 'رویدادها'},
        ),
    ]
