# Generated by Django 3.0.6 on 2020-06-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0009_auto_20200615_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
