# Generated by Django 3.0.6 on 2020-08-01 13:28

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0011_auto_20200715_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(null=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='event',
            name='file_url',
            field=models.CharField(blank=True, max_length=750, null=True, verbose_name='لینک دانلود فایل'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='images/events', verbose_name='تصویر شاخص'),
        ),
        migrations.AlterField(
            model_name='event',
            name='person',
            field=models.CharField(max_length=70, null=True, verbose_name='ارائه دهنده'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('a', 'به اتمام رسیده'), ('b', 'آغاز شده'), ('c', 'برگزار نشده')], max_length=1, null=True, verbose_name='وضعیت برگزاری'),
        ),
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.TextField(max_length=250, null=True, verbose_name='خلاصه'),
        ),
        migrations.AlterField(
            model_name='event',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='لینک ویدیو یوتوب'),
        ),
    ]
