# Generated by Django 3.0.6 on 2020-06-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0011_category_mother'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_url',
            field=models.CharField(blank=True, max_length=750, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='refrence',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=750, null=True),
        ),
    ]
