# Generated by Django 3.0.6 on 2020-06-23 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0016_auto_20200616_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='mother',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='app_blog.Category'),
        ),
    ]
