# Generated by Django 3.0.6 on 2020-06-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0021_auto_20200625_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(max_length=120, null=True),
        ),
    ]
