# Generated by Django 3.0.6 on 2020-06-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0023_auto_20200629_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
