# Generated by Django 3.0.6 on 2020-07-17 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0027_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_reply',
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('d', 'در انتظار تایید'), ('a', 'تایید شده')], default='d', max_length=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='app_blog.Comment'),
        ),
    ]
