# Generated by Django 3.0.6 on 2020-07-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0029_auto_20200719_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(choices=[('a', 'تبلیغات'), ('b', 'همکاری تجاری'), ('c', 'برگزاری رویداد'), ('d', 'درخواست همکاری'), ('e', 'سایر')], max_length=1, null=True)),
                ('message', models.TextField(max_length=1500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
