# Generated by Django 3.0.6 on 2020-07-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0030_auto_20200720_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mail',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
