# Generated by Django 3.0.6 on 2020-07-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0031_auto_20200720_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='description',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title',
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(null=True, upload_to='images/slider', verbose_name='تصویر'),
        ),
    ]
