# Generated by Django 3.0.6 on 2020-07-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0032_auto_20200731_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.CharField(blank=True, help_text='پیوند باید کامل و همراه با http باشد.', max_length=1200, null=True, verbose_name='پیوند'),
        ),
    ]
