# Generated by Django 3.0.6 on 2020-07-31 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0033_auto_20200731_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='title',
        ),
    ]
