# Generated by Django 3.0.6 on 2020-08-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0035_auto_20200801_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, null=True, verbose_name='پیوند'),
        ),
    ]
