# Generated by Django 3.0.6 on 2020-08-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0037_auto_20200801_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('s', 'دیده شده'), ('d', 'دیده نشده')], default='s', max_length=1, null=True, verbose_name='وضعیت'),
        ),
    ]
