# Generated by Django 3.0.6 on 2020-08-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0041_post_publish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده')], max_length=9, null=True, verbose_name='وضعیت انتشار'),
        ),
    ]
