# Generated by Django 3.0.6 on 2020-08-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0044_auto_20200820_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_time',
            field=models.DateTimeField(blank=True, help_text='در صورتی که مایل هستید پست به صورت خودکار منتشر شود تاریخ و ساعت مورد نظر را انتخاب کنید. در غیر این صورت این فیلد را خالی بگذارید.', null=True, verbose_name='زمانبندی انتشار'),
        ),
    ]
