# Generated by Django 3.0.6 on 2020-09-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0045_auto_20200830_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_alt',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='متن جایگزین'),
        ),
    ]
