# Generated by Django 3.0.6 on 2020-08-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/admin'),
        ),
        migrations.AlterField(
            model_name='files',
            name='calender',
            field=models.FileField(null=True, upload_to='uploads/admin'),
        ),
        migrations.AlterField(
            model_name='files',
            name='instagram',
            field=models.FileField(null=True, upload_to='uploads/admin'),
        ),
        migrations.AlterField(
            model_name='files',
            name='site',
            field=models.FileField(null=True, upload_to='uploads/admin'),
        ),
    ]
