# Generated by Django 3.0.6 on 2020-08-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_auto_20200820_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='calender',
        ),
        migrations.RemoveField(
            model_name='files',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='files',
            name='site',
        ),
        migrations.AddField(
            model_name='files',
            name='admin_file',
            field=models.FileField(null=True, upload_to='uploads/admin'),
        ),
        migrations.AddField(
            model_name='files',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
