"""
Django settings for cgc_site project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@a67vhz%s8&@&4_5=)xu+f&++-)*)4=8p3$it4$t+c-ckc))(7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ALLOWED_HOSTS = ['cgeeksc.ir', 'www.cgeeksc.ir', '185.211.58.239', '198.211.99.20', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'app_blog.apps.AppBlogConfig',
    'app_event.apps.AppEventConfig',
    'app_account.apps.AppAccountConfig',
    'app_project',
    
    'django.contrib.sitemaps',

    'sorl.thumbnail',
    # 'social_django',
    'crispy_forms',
    'django_social_share',
    'ckeditor',
    'ckeditor_uploader',
    'django_jalali',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

        # 'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'cgc_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR + '/templates/',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # 'social_django.context_processors.backends', 
                # 'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'cgc_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'cgcdb',
        'USER': 'cgcuser',
        'PASSWORD': '12345678',
        'HOST': '127.0.0.1',
    }

    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'cgcdb',
    #     'USER': 'cgcdbuser',
    #     'PASSWORD': 'Cgc962008580Reza@',
    #     'HOST': 'localhost',
    # }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'static'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# AUTHENTICATION_BACKENDS = (
#     'social_core.backends.open_id.OpenIdAuth',
#     'social_core.backends.google.GoogleOpenId',
#     'social_core.backends.google.GoogleOAuth2',
#     'social_core.backends.google.GoogleOAuth',
#     'social_core.backends.github.GithubOAuth2',

#     'django.contrib.auth.backends.ModelBackend',
# )

LOGIN_URL = 'app-account:login'
LOGOUT_URL = 'app-account:logout'
redirect_field_name='app-account:login'
LOGIN_REDIRECT_URL = 'app-blog:home'

# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '441533382913-nltcm6umcubsd23ataak15nipghonbeb.apps.googleusercontent.com'
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'sV8ZJCrCF6Ge10Jf7DWqrWuu'

CRISPY_TEMPLATE_PACK = 'bootstrap4'
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880

POST_404 = STATIC_URL + '/images/404.jpg'
POST_TH404 = STATIC_URL + '/images/th404.jpg'
AVATAR_404 = STATIC_URL + '/images/a404.png'

CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"
CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'font_names': 'Vazir', #'IRANSans; Yekan; Bnasim; Bkoodak;,
        'font_size': 32,
        'width': 1200,
        'height:': 750,
    },
}


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'cgeeksc.info@gmail.com'
EMAIL_HOST_PASSWORD = 'aqSWH4sf8B2TuFZ'

