# Generated by Django 3.0.6 on 2020-07-23 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0002_auto_20200723_2348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='PCategory',
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
    ]
